In [1]:
import numpy as np
import time

In [11]:
size = 10_00_000



lst = list(range(size))
start = time.time()
sq_lst = [x**2 for x in lst]
end = time.time()
print(f"Python list time = {end - start} seconds")

arr = np.array(lst)
start = time.time()
sq_arr = arr ** 2
end = time.time()
print(f"Numpy list time = {end - start} seconds")

Python list time = 0.11446666717529297 seconds
Numpy list time = 0.0048046112060546875 seconds


In [16]:
import sys
print(f"Python list size = {sys.getsizeof(lst) * len(lst)} bytes")
print(f"Numpy array size = {arr.nbytes} bytes")

Python list size = 8000056000000 bytes
Numpy array size = 8000000 bytes


In [25]:
arr1 = np.zeros((2, 3), dtype="int64") #creates a array with zeros
print(arr1, arr1.shape)

[[0 0 0]
 [0 0 0]] (2, 3)


In [28]:
arr2 = np.ones((6,), dtype="int64")  #creates a array with ones
print(arr2, arr2.shape)

[1 1 1 1 1 1] (6,)


In [35]:
arr3 = np.full((4,3), 100)  #creates a array with the no given
print(arr3, arr3.shape)

[[100 100 100]
 [100 100 100]
 [100 100 100]
 [100 100 100]] (4, 3)


In [36]:
arr4 = np.eye((6)) # creates a identity matrix
print(arr4)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [39]:
arr5 = np.arange(1, 11, 1) # creates array with a range
print(arr5)

[ 1  2  3  4  5  6  7  8  9 10]


In [60]:
arr6 = np.linspace(0, 100, 11) # Evenly spaced arrays
print(arr6)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [66]:
arr7 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr7.shape)
print(arr7.shape)
print(arr7.dtype)

float_arr = arr7.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
(3, 3)
int64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [74]:
arr8 = np.array([[1,2,3], [4,5,6]])
print(arr8, arr8.shape)

arr_reshaped = arr8.reshape((3,2))
print(arr_reshaped, arr_reshaped.shape)

arr_1D = arr8.flatten() 
print(arr_1D)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]
