In [1]:
import numpy as np
import time

In [11]:
size = 10_00_000



lst = list(range(size))
start = time.time()
sq_lst = [x**2 for x in lst]
end = time.time()
print(f"Python list time = {end - start} seconds")

arr = np.array(lst)
start = time.time()
sq_arr = arr ** 2
end = time.time()
print(f"Numpy list time = {end - start} seconds")

Python list time = 0.11446666717529297 seconds
Numpy list time = 0.0048046112060546875 seconds


In [16]:
import sys
print(f"Python list size = {sys.getsizeof(lst) * len(lst)} bytes")
print(f"Numpy array size = {arr.nbytes} bytes")

Python list size = 8000056000000 bytes
Numpy array size = 8000000 bytes


In [25]:
arr1 = np.zeros((2, 3), dtype="int64") #creates a array with zeros
print(arr1, arr1.shape)

[[0 0 0]
 [0 0 0]] (2, 3)


In [28]:
arr2 = np.ones((6,), dtype="int64")  #creates a array with ones
print(arr2, arr2.shape)

[1 1 1 1 1 1] (6,)


In [35]:
arr3 = np.full((4,3), 100)  #creates a array with the no given
print(arr3, arr3.shape)

[[100 100 100]
 [100 100 100]
 [100 100 100]
 [100 100 100]] (4, 3)


In [36]:
arr4 = np.eye((6)) # creates a identity matrix
print(arr4)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [39]:
arr5 = np.arange(1, 11, 1) # creates array with a range
print(arr5)

[ 1  2  3  4  5  6  7  8  9 10]


In [60]:
arr6 = np.linspace(0, 100, 11) # Evenly spaced arrays
print(arr6)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [8]:
# Type changing
arr7 = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr7.shape)
print(arr7.shape)
print(arr7.dtype)

float_arr = arr7.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
(3, 3)
int64
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [9]:
# Reshaping

arr8 = np.array([[1,2,3], [4,5,6]])
print(arr8, arr8.shape)

arr_reshaped = arr8.reshape((3,2))
print(arr_reshaped, arr_reshaped.shape)

arr_1D = arr8.flatten() 
print(arr_1D)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]


In [15]:
# indexing
arr9 = np.array([1,2,3,4,5])
arr10 = np.array([[1,2,3], [4,5,6]])

print(arr9[3])

print(arr10[1][1])

idx = [1,3,4]
print(arr9[idx])

print(arr9[arr9 > 2])

4
5
[2 4 5]
[3 4 5]


In [18]:
#Slicing
arr11 = np.array([1,2,3,4,5])

print(arr11[1:4])
print(arr11[0:4:2])
print(arr11[1::3])
print(arr11[:4])
print(arr11[::2])
print(arr11[::-1])

[2 3 4]
[1 3]
[2 5]
[1 2 3 4]
[1 3 5]
[5 4 3 2 1]


In [40]:
# Multi Dimentional Array
# 2d  array
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
print(arr_2d.sum())

sum_of_cols = np.sum(arr_2d, axis=0)
print(sum_of_cols)
sum_of_rows = np.sum(arr_2d, axis=1)
print(sum_of_rows)

print(arr_2d[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [55]:
# 3D array

arr3d = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) # 2 x 3 x 2
print(arr3d, arr3d.shape)
# indexing
print(arr3d[0,1,1])
# slicing
print(arr3d[:,0,:]) # first row from both layers
print(arr3d[:,:,0]) # first col from both layers

arr3d[:,0,:] = 99
print(arr3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [59]:
# Vectorization

arr12 = np.array([1,2,3,4,5,6,7])
arr13 = np.array([8,9,10,11,12,13, 14])

print(arr12 ** 2)
print(arr12 + 10)
print(arr12+arr13)

[ 1  4  9 16 25 36 49]
[11 12 13 14 15 16 17]
[ 9 11 13 15 17 19 21]


In [7]:
# Normalize

arr14 = np.array([[1,2], [3,4]])
mean = np.mean(arr14)  
std_dev = np.std(arr14)

normalized_arr = (arr14-mean)/std_dev
print(normalized_arr)
print(mean) 
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
